
import java.util.*;
import javax.swing.ImageIcon;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import java.util.*;
import javax.swing.ImageIcon;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Chi
 */
public class MatchingGameApp extends javax.swing.JFrame {
    //creates variable for ArrayList
    ArrayList <String> cards = new ArrayList();
    ArrayList <String> set = new ArrayList();
    ImageIcon a = new ImageIcon ("ram.jpg");
    ImageIcon b = new ImageIcon ("case.jpg");
    ImageIcon c = new ImageIcon ("dvd.jpg");
    ImageIcon d = new ImageIcon ("harddrive.jpg");
    ImageIcon e = new ImageIcon ("keyboard.jpg");
    ImageIcon f = new ImageIcon ("mice.jpg");
    ImageIcon g = new ImageIcon ("monitor.jpg");
    ImageIcon h = new ImageIcon ("printer.jpg");
    ImageIcon back = new ImageIcon ("cardback.jpg");
    ImageIcon done = new ImageIcon ("done.jpg");
    int count, c1, c2, card1,card2;
    int cardsLeft = 16;
    int[] change = new int [16];
    
    
    /**
     * Creates new form ChangeApp
     */
    public MatchingGameApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblChangeExchangeTitle = new javax.swing.JLabel();
        Card1 = new javax.swing.JButton();
        Card2 = new javax.swing.JButton();
        Card3 = new javax.swing.JButton();
        Card4 = new javax.swing.JButton();
        Card5 = new javax.swing.JButton();
        Card6 = new javax.swing.JButton();
        Card7 = new javax.swing.JButton();
        Card8 = new javax.swing.JButton();
        Card9 = new javax.swing.JButton();
        Card10 = new javax.swing.JButton();
        Card11 = new javax.swing.JButton();
        Card12 = new javax.swing.JButton();
        Card13 = new javax.swing.JButton();
        Card14 = new javax.swing.JButton();
        Card15 = new javax.swing.JButton();
        Card16 = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        btnGuess = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtCalcOutput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblChangeExchangeTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblChangeExchangeTitle.setForeground(new java.awt.Color(255, 51, 51));
        lblChangeExchangeTitle.setText("Matching Game");

        Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardback.jpg"))); // NOI18N
        Card1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card1MouseClicked(evt);
            }
        });

        Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardback.jpg"))); // NOI18N
        Card2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card2MouseClicked(evt);
            }
        });

        Card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardback.jpg"))); // NOI18N
        Card3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card3MouseClicked(evt);
            }
        });

        Card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardback.jpg"))); // NOI18N
        Card4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card4MouseClicked(evt);
            }
        });

        Card5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardback.jpg"))); // NOI18N
        Card5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card5MouseClicked(evt);
            }
        });

        Card6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardback.jpg"))); // NOI18N
        Card6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card6MouseClicked(evt);
            }
        });

        Card7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardback.jpg"))); // NOI18N
        Card7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card7MouseClicked(evt);
            }
        });

        Card8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardback.jpg"))); // NOI18N
        Card8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card8MouseClicked(evt);
            }
        });

        Card9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardback.jpg"))); // NOI18N
        Card9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card9MouseClicked(evt);
            }
        });

        Card10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardback.jpg"))); // NOI18N
        Card10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card10MouseClicked(evt);
            }
        });

        Card11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardback.jpg"))); // NOI18N
        Card11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card11MouseClicked(evt);
            }
        });

        Card12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardback.jpg"))); // NOI18N
        Card12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card12MouseClicked(evt);
            }
        });

        Card13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardback.jpg"))); // NOI18N
        Card13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card13MouseClicked(evt);
            }
        });

        Card14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardback.jpg"))); // NOI18N
        Card14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card14MouseClicked(evt);
            }
        });

        Card15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardback.jpg"))); // NOI18N
        Card15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card15MouseClicked(evt);
            }
        });

        Card16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cardback.jpg"))); // NOI18N
        Card16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Card16MouseClicked(evt);
            }
        });

        btnPlay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPlay.setText("Play");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnGuess.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuess.setText("Guess Again");
        btnGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuessActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        txtCalcOutput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCalcOutput.setText("Click the Play button to start. Make sure to click Guess Again after each guess.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(lblChangeExchangeTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Card5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Card6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Card7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Card8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Card1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Card2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Card3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Card4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Card9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Card10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Card11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Card12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Card13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Card14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Card15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Card16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 94, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGuess)
                        .addGap(42, 42, 42)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtCalcOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblChangeExchangeTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Card2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(Card1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Card3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Card7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Card5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Card6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Card4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Card8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Card10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Card12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Card11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Card16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Card15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Card14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Card9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Card13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnPlay)
                    .addComponent(btnGuess))
                .addGap(18, 18, 18)
                .addComponent(txtCalcOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0); // Exit the application.
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
        
        // set change array
        for (int z=0; z<=15; z++) {
            change [z] = 1;
        }
        
        // assign cards at random
        String temp;
        for (int x=0; x<=7; x++) {
        for (int y=1; y<=2; y++) {
            temp = Integer.toString(x);
            set.add(temp);
            }
        }
        for (int x=0; x<=15; x++) {
            double index = Math.floor(Math.random()*(16-x));
            int index1 = (int) index;
            cards.add(set.get(index1));
            set.remove(set.get(index1));
        }
    }//GEN-LAST:event_btnPlayActionPerformed

    private void Card1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card1MouseClicked
        // TODO add your handling code here:
                String temp = cards.get(0);

        if (temp.equals ("0")) {
            Card1.setIcon(a);
        } else if (temp.equals ("1")) {
            Card1.setIcon(b);
        } else if (temp.equals ("2")) {
            Card1.setIcon(c);
        } else if (temp.equals ("3")) {
            Card1.setIcon(d);
        } else if (temp.equals ("4")) {
            Card1.setIcon(e);
        } else if (temp.equals ("5")) {
            Card1.setIcon(f);
        } else if (temp.equals ("6")) {
            Card1.setIcon(g);
        } else if (temp.equals ("7")) {
            Card1.setIcon(h);
        }
        count++;
        if (count==1){
            c1=Integer.parseInt(temp);
            change[0]=0;
        } else if (count==2){
            c2=Integer.parseInt(temp);
            change[0]=0;
        }
    }//GEN-LAST:event_Card1MouseClicked

    private void Card2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card2MouseClicked
        // TODO add your handling code here:
                String temp = cards.get(0);

        if (temp.equals ("0")) {
            Card2.setIcon(a);
        } else if (temp.equals ("1")) {
            Card2.setIcon(b);
        } else if (temp.equals ("2")) {
            Card2.setIcon(c);
        } else if (temp.equals ("3")) {
            Card2.setIcon(d);
        } else if (temp.equals ("4")) {
            Card2.setIcon(e);
        } else if (temp.equals ("5")) {
            Card2.setIcon(f);
        } else if (temp.equals ("6")) {
            Card2.setIcon(g);
        } else if (temp.equals ("7")) {
            Card2.setIcon(h);
        }
        count++;
        if (count==1){
            c1=Integer.parseInt(temp);
            change[0]=0;
        } else if (count==2){
            c2=Integer.parseInt(temp);
            change[0]=0;
        }
    }//GEN-LAST:event_Card2MouseClicked

    private void Card3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card3MouseClicked
        // TODO add your handling code here:
                String temp = cards.get(2);

        if (temp.equals ("0")) {
            Card3.setIcon(a);
        } else if (temp.equals ("1")) {
            Card3.setIcon(b);
        } else if (temp.equals ("2")) {
            Card3.setIcon(c);
        } else if (temp.equals ("3")) {
            Card3.setIcon(d);
        } else if (temp.equals ("4")) {
            Card3.setIcon(e);
        } else if (temp.equals ("5")) {
            Card3.setIcon(f);
        } else if (temp.equals ("6")) {
            Card3.setIcon(g);
        } else if (temp.equals ("7")) {
            Card3.setIcon(h);
        }

        count++;
        if (count==1){
            c1=Integer.parseInt(temp);
            change[2]=0;
        } else {
            c2=Integer.parseInt(temp);
            change[2]=0;
        }
    }//GEN-LAST:event_Card3MouseClicked

    private void Card4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card4MouseClicked
        // TODO add your handling code here:
                String temp = cards.get(3);

        if (temp.equals ("0")) {
            Card4.setIcon(a);
        } else if (temp.equals ("1")) {
            Card4.setIcon(b);
        } else if (temp.equals ("2")) {
            Card4.setIcon(c);
        } else if (temp.equals ("3")) {
            Card4.setIcon(d);
        } else if (temp.equals ("4")) {
            Card4.setIcon(e);
        } else if (temp.equals ("5")) {
            Card4.setIcon(f);
        } else if (temp.equals ("6")) {
            Card4.setIcon(g);
        } else if (temp.equals ("7")) {
            Card4.setIcon(h);
        }

        count++;
        if (count==1){
            c1=Integer.parseInt(temp);
            change[3]=0;
        } else {
            c2=Integer.parseInt(temp);
            change[3]=0;
        }

    }//GEN-LAST:event_Card4MouseClicked

    private void Card5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card5MouseClicked
        // TODO add your handling code here:
                String temp = cards.get(4);

        if (temp.equals ("0")) {
            Card5.setIcon(a);
        } else if (temp.equals ("1")) {
            Card5.setIcon(b);
        } else if (temp.equals ("2")) {
            Card5.setIcon(c);
        } else if (temp.equals ("3")) {
            Card5.setIcon(d);
        } else if (temp.equals ("4")) {
            Card5.setIcon(e);
        } else if (temp.equals ("5")) {
            Card5.setIcon(f);
        } else if (temp.equals ("6")) {
            Card5.setIcon(g);
        } else if (temp.equals ("7")) {
            Card5.setIcon(h);
        }

        count++;
        if (count==1){
            c1=Integer.parseInt(temp);
            change[4]=0;
        } else {
            c2=Integer.parseInt(temp);
            change[4]=0;
        }

    }//GEN-LAST:event_Card5MouseClicked

    private void Card6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card6MouseClicked
        // TODO add your handling code here:
                String temp = cards.get(5);

        if (temp.equals ("0")) {
            Card6.setIcon(a);
        } else if (temp.equals ("1")) {
            Card6.setIcon(b);
        } else if (temp.equals ("2")) {
            Card6.setIcon(c);
        } else if (temp.equals ("3")) {
            Card6.setIcon(d);
        } else if (temp.equals ("4")) {
            Card6.setIcon(e);
        } else if (temp.equals ("5")) {
            Card6.setIcon(f);
        } else if (temp.equals ("6")) {
            Card6.setIcon(g);
        } else if (temp.equals ("7")) {
            Card6.setIcon(h);
        }

        count++;
        if (count==1){
            c1=Integer.parseInt(temp);
            change[5]=0;
        } else {
            c2=Integer.parseInt(temp);
            change[5]=0;
        }

    }//GEN-LAST:event_Card6MouseClicked

    private void Card7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card7MouseClicked
        // TODO add your handling code here:
                String temp = cards.get(6);

        if (temp.equals ("0")) {
            Card7.setIcon(a);
        } else if (temp.equals ("1")) {
            Card7.setIcon(b);
        } else if (temp.equals ("2")) {
            Card7.setIcon(c);
        } else if (temp.equals ("3")) {
            Card7.setIcon(d);
        } else if (temp.equals ("4")) {
            Card7.setIcon(e);
        } else if (temp.equals ("5")) {
            Card7.setIcon(f);
        } else if (temp.equals ("6")) {
            Card7.setIcon(g);
        } else if (temp.equals ("7")) {
            Card7.setIcon(h);
        }

        count++;
        if (count==1){
            c1=Integer.parseInt(temp);
            change[6]=0;
        } else {
            c2=Integer.parseInt(temp);
            change[6]=0;
        }
    }//GEN-LAST:event_Card7MouseClicked

    private void Card8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card8MouseClicked
        // TODO add your handling code here:
                String temp = cards.get(7);

        if (temp.equals ("0")) {
            Card8.setIcon(a);
        } else if (temp.equals ("1")) {
            Card8.setIcon(b);
        } else if (temp.equals ("2")) {
            Card8.setIcon(c);
        } else if (temp.equals ("3")) {
            Card8.setIcon(d);
        } else if (temp.equals ("4")) {
            Card8.setIcon(e);
        } else if (temp.equals ("5")) {
            Card8.setIcon(f);
        } else if (temp.equals ("6")) {
            Card8.setIcon(g);
        } else if (temp.equals ("7")) {
            Card8.setIcon(h);
        }

        count++;
        if (count==1){
            c1=Integer.parseInt(temp);
            change[7]=0;
        } else {
            c2=Integer.parseInt(temp);
            change[7]=0;
        }
    }//GEN-LAST:event_Card8MouseClicked

    private void Card9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card9MouseClicked
        // TODO add your handling code here:
                String temp = cards.get(8);

        if (temp.equals ("0")) {
            Card9.setIcon(a);
        } else if (temp.equals ("1")) {
            Card9.setIcon(b);
        } else if (temp.equals ("2")) {
            Card9.setIcon(c);
        } else if (temp.equals ("3")) {
            Card9.setIcon(d);
        } else if (temp.equals ("4")) {
            Card9.setIcon(e);
        } else if (temp.equals ("5")) {
            Card9.setIcon(f);
        } else if (temp.equals ("6")) {
            Card9.setIcon(g);
        } else if (temp.equals ("7")) {
            Card9.setIcon(h);
        }

        count++;
        if (count==1){
            c1=Integer.parseInt(temp);
            change[8]=0;
        } else {
            c2=Integer.parseInt(temp);
            change[8]=0;
        }
    }//GEN-LAST:event_Card9MouseClicked

    private void Card10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card10MouseClicked
        // TODO add your handling code here:
                String temp = cards.get(9);

        if (temp.equals ("0")) {
            Card10.setIcon(a);
        } else if (temp.equals ("1")) {
            Card10.setIcon(b);
        } else if (temp.equals ("2")) {
            Card10.setIcon(c);
        } else if (temp.equals ("3")) {
            Card10.setIcon(d);
        } else if (temp.equals ("4")) {
            Card10.setIcon(e);
        } else if (temp.equals ("5")) {
            Card10.setIcon(f);
        } else if (temp.equals ("6")) {
            Card10.setIcon(g);
        } else if (temp.equals ("7")) {
            Card10.setIcon(h);
        }

        count++;
        if (count==1){
            c1=Integer.parseInt(temp);
            change[9]=0;
        } else {
            c2=Integer.parseInt(temp);
            change[9]=0;
        }
    }//GEN-LAST:event_Card10MouseClicked

    private void Card11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card11MouseClicked
        // TODO add your handling code here:
                String temp = cards.get(10);

        if (temp.equals ("0")) {
            Card11.setIcon(a);
        } else if (temp.equals ("1")) {
            Card11.setIcon(b);
        } else if (temp.equals ("2")) {
            Card11.setIcon(c);
        } else if (temp.equals ("3")) {
            Card11.setIcon(d);
        } else if (temp.equals ("4")) {
            Card11.setIcon(e);
        } else if (temp.equals ("5")) {
            Card11.setIcon(f);
        } else if (temp.equals ("6")) {
            Card11.setIcon(g);
        } else if (temp.equals ("7")) {
            Card11.setIcon(h);
        }

        count++;
        if (count==1){
            c1=Integer.parseInt(temp);
            change[10]=0;
        } else {
            c2=Integer.parseInt(temp);
            change[10]=0;
        }

    }//GEN-LAST:event_Card11MouseClicked

    private void Card12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card12MouseClicked
        // TODO add your handling code here:
                String temp = cards.get(11);

        if (temp.equals ("0")) {
            Card12.setIcon(a);
        } else if (temp.equals ("1")) {
            Card12.setIcon(b);
        } else if (temp.equals ("2")) {
            Card12.setIcon(c);
        } else if (temp.equals ("3")) {
            Card12.setIcon(d);
        } else if (temp.equals ("4")) {
            Card12.setIcon(e);
        } else if (temp.equals ("5")) {
            Card12.setIcon(f);
        } else if (temp.equals ("6")) {
            Card12.setIcon(g);
        } else if (temp.equals ("7")) {
            Card12.setIcon(h);
        }

        count++;
        if (count==1){
            c1=Integer.parseInt(temp);
            change[11]=0;
        } else {
            c2=Integer.parseInt(temp);
            change[11]=0;
        }
    }//GEN-LAST:event_Card12MouseClicked

    private void Card13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card13MouseClicked
        // TODO add your handling code here:
        String temp = cards.get(12);

        if (temp.equals ("0")) {
            Card13.setIcon(a);
        } else if (temp.equals ("1")) {
            Card13.setIcon(b);
        } else if (temp.equals ("2")) {
            Card13.setIcon(c);
        } else if (temp.equals ("3")) {
            Card13.setIcon(d);
        } else if (temp.equals ("4")) {
            Card13.setIcon(e);
        } else if (temp.equals ("5")) {
            Card13.setIcon(f);
        } else if (temp.equals ("6")) {
            Card13.setIcon(g);
        } else if (temp.equals ("7")) {
            Card13.setIcon(h);
        }

        count++;
        if (count==1){
            c1=Integer.parseInt(temp);
            change[12]=0;
        } else {
            c2=Integer.parseInt(temp);
            change[12]=0;
        }
    }//GEN-LAST:event_Card13MouseClicked

    private void Card14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card14MouseClicked
        // TODO add your handling code here:
                String temp = cards.get(13);

        if (temp.equals ("0")) {
            Card14.setIcon(a);
        } else if (temp.equals ("1")) {
            Card14.setIcon(b);
        } else if (temp.equals ("2")) {
            Card14.setIcon(c);
        } else if (temp.equals ("3")) {
            Card14.setIcon(d);
        } else if (temp.equals ("4")) {
            Card14.setIcon(e);
        } else if (temp.equals ("5")) {
            Card14.setIcon(f);
        } else if (temp.equals ("6")) {
            Card14.setIcon(g);
        } else if (temp.equals ("7")) {
            Card14.setIcon(h);
        }

        count++;
        if (count==1){
            c1=Integer.parseInt(temp);
            change[13]=0;
        } else {
            c2=Integer.parseInt(temp);
            change[13]=0;
        }
    }//GEN-LAST:event_Card14MouseClicked

    private void Card15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card15MouseClicked
        // TODO add your handling code here:
                String temp = cards.get(14);

        if (temp.equals ("0")) {
            Card15.setIcon(a);
        } else if (temp.equals ("1")) {
            Card15.setIcon(b);
        } else if (temp.equals ("2")) {
            Card15.setIcon(c);
        } else if (temp.equals ("3")) {
            Card15.setIcon(d);
        } else if (temp.equals ("4")) {
            Card15.setIcon(e);
        } else if (temp.equals ("5")) {
            Card15.setIcon(f);
        } else if (temp.equals ("6")) {
            Card15.setIcon(g);
        } else if (temp.equals ("7")) {
            Card15.setIcon(h);
        }

        count++;
        if (count==1){
            c1=Integer.parseInt(temp);
            change[14]=0;
        } else {
            c2=Integer.parseInt(temp);
            change[14]=0;
        }

    }//GEN-LAST:event_Card15MouseClicked

    private void Card16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Card16MouseClicked
        // TODO add your handling code here:
                String temp = cards.get(15);

        if (temp.equals ("0")) {
            Card16.setIcon(a);
        } else if (temp.equals ("1")) {
            Card16.setIcon(b);
        } else if (temp.equals ("2")) {
            Card16.setIcon(c);
        } else if (temp.equals ("3")) {
            Card16.setIcon(d);
        } else if (temp.equals ("4")) {
            Card16.setIcon(e);
        } else if (temp.equals ("5")) {
            Card16.setIcon(f);
        } else if (temp.equals ("6")) {
            Card16.setIcon(g);
        } else if (temp.equals ("7")) {
            Card16.setIcon(h);
        }
        
        count++;
        if (count==1){
            c1=Integer.parseInt(temp);
            change[15]=0;
        } else {
            c2=Integer.parseInt(temp);
            change[15]=0;
        }

    }//GEN-LAST:event_Card16MouseClicked

    private void btnGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuessActionPerformed
        // TODO add your handling code here:
                count = 0;
        if (c1==c2){
            for (int y=1; y<=2; y++) {
            if (change[0]==0){
                Card1.setIcon(done);
                Card1.setEnabled(false);
                change[0]=2;
            } else if (change[1]==0) {
                Card2.setIcon(done);
                change[1]=2;
            } else if (change[2]==0) {
                Card3.setIcon(done);
                change[2]=2;
            } else if (change[3]==0) {
                Card4.setIcon(done);
                change[3]=2;
            } else if (change[4]==0) {
                Card5.setIcon(done);
                change[4]=2;
            } else if (change[5]==0) {
                Card6.setIcon(done);
                change[5]=2;
            } else if (change[6]==0) {
                Card7.setIcon(done);
                change[6]=2;
            } else if (change[7]==0) {
                Card8.setIcon(done);
                change[7]=2;
            } else if (change[8]==0) {
                Card9.setIcon(done);
                change[8]=2;
            } else if (change[9]==0) {
                Card10.setIcon(done);
                change[9]=2;
            } else if (change[10]==0) {
                Card11.setIcon(done);
                change[10]=2;
            } else if (change[11]==0) {
                Card12.setIcon(done);
                change[11]=2;
            } else if (change[12]==0) {
                Card13.setIcon(done);
                change[12]=2;
            } else if (change[13]==0) {
                Card14.setIcon(done);
                change[13]=2;
            } else if (change[14]==0) {
                Card15.setIcon(done);
                change[14]=2;
            } else if (change[15]==0) {
                Card16.setIcon(done);
                change[15]=2;
            }
            }
     } else {
            for (int y=1; y<=2; y++){
            if (change[0]==0){
                Card1.setIcon(back);
                change[0]=1;
            } else if (change[1]==0) {
                Card2.setIcon(back);
                change[1]=1;
            } else if (change[2]==0) {
                Card3.setIcon(back);
                change[2]=1;
            } else if (change[3]==0) {
                Card4.setIcon(back);
                change[3]=1;
            } else if (change[4]==0) {
                Card5.setIcon(back);
                change[4]=1;
            } else if (change[5]==0) {
                Card6.setIcon(back);
                change[5]=1;
            } else if (change[6]==0) {
                Card7.setIcon(back);
                change[6]=1;
            } else if (change[7]==0) {
                Card8.setIcon(back);
                change[7]=1;
            } else if (change[8]==0) {
                Card9.setIcon(back);
                change[8]=1;
            } else if (change[9]==0) {
                Card10.setIcon(back);
                change[9]=1;
            } else if (change[10]==0) {
                Card11.setIcon(back);
                change[10]=1;
            } else if (change[11]==0) {
                Card12.setIcon(back);
                change[11]=1;
            } else if (change[12]==0) {
                Card13.setIcon(back);
                change[12]=1;
            } else if (change[13]==0) {
                Card14.setIcon(back);
                change[13]=1;
            } else if (change[14]==0) {
                Card15.setIcon(back);
                change[14]=1;
            } else if (change[15]==0) {
                Card16.setIcon(back);
                change[15]=1;
            }
            }
     }
    }//GEN-LAST:event_btnGuessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatchingGameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatchingGameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatchingGameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatchingGameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatchingGameApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Card1;
    private javax.swing.JButton Card10;
    private javax.swing.JButton Card11;
    private javax.swing.JButton Card12;
    private javax.swing.JButton Card13;
    private javax.swing.JButton Card14;
    private javax.swing.JButton Card15;
    private javax.swing.JButton Card16;
    private javax.swing.JButton Card2;
    private javax.swing.JButton Card3;
    private javax.swing.JButton Card4;
    private javax.swing.JButton Card5;
    private javax.swing.JButton Card6;
    private javax.swing.JButton Card7;
    private javax.swing.JButton Card8;
    private javax.swing.JButton Card9;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGuess;
    private javax.swing.JButton btnPlay;
    private javax.swing.JLabel lblChangeExchangeTitle;
    private javax.swing.JTextField txtCalcOutput;
    // End of variables declaration//GEN-END:variables
}
